language: node_js
node_js:
  - 12
cache: npm
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  local_dir: dist
  target_branch: master
  on:
    branch: master
  github_token: $GH_TOKEN
  skip_cleanup: true
  keep_history: true
  committer_from_gh: true